name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - .github/workflows/copilot-setup-steps.yml
      - Autoversion
      - Claude
      - CodeQL
      - Copilot cloud agent
      - Copilot code review
      - Copilot coding agent
      - OpenAI Codex
      - Recompile Agentic Workflows
      - Renovate
      - Validate Renovate Config
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@af83be0ddf1ec3035230c030f3ab6d10a7040515 # v5.56.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
